import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";
import SnackbarWrapper from "./components/SnackbarWrapper";
import Header from "./components/Header/Header";
import GalleryWrapper from "./components/GalleryWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/static/favicon.png",
        href: "/static/favicon.png",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <link rel="icon" href="/static/favicon.png" sizes="any" />
        <Providers>
          <main className="select-none relative transition-all bg-light font-main dark:bg-dark min-h-dvh w-full flex flex-col lg2:px-24 lg2:py-4">
            <SnackbarWrapper />
            <GalleryWrapper />
            <Header />
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
