export const acceptedRouteNames: string[] = ["scrap", "statues", "treasures"];
export const acceptedRouteGames: string[] = ["cs", "gta"];

type HardcodedPositions = {
  [key: string]: {
    [key: string]: {
      top: string;
      left: string;
    };
  };
};

export const Locations: string[] = [
  "All locations",
  "Calafia",
  "Sawmill",
  "Timber tunnel",
  "Gino's place",
  "First bridge",
  "Second bridge",
  "Plane",
  "Epsylon",
  "Farm",
  "Chilliad",
  "Ranch",
  "Paleto",
  "FZ",
  "Behind SAHP",
];

export type MapsState = {
  name: string;
  logo: string;
  image: string;
  radar: string[];
};

export const Maps: MapsState[] = [
  {
    name: "Anubis",
    logo: "/static/cs/logo/anubisLogo.png",
    image: "/static/cs/wallpaper/anubis.jpg",
    radar: ["https://assets.csnades.gg/anubis_game_radar_7bada7b5e9.webp"],
  },
  {
    name: "Ancient",
    logo: "/static/cs/logo/ancientLogo.webp",
    image: "/static/cs/wallpaper/ancient.jpg",
    radar: ["https://assets.csnades.gg/ancient_game_radar_14875e0cb1.webp"],
  },
  {
    name: "Inferno",
    logo: "/static/cs/logo/infernoLogo.png",
    image: "/static/cs/wallpaper/inferno.jpeg",
    radar: ["https://assets.csnades.gg/inferno_game_radar_bbecda6217.webp"],
  },
  {
    name: "Mirage",
    logo: "/static/cs/logo/mirageLogo.png",
    image: "/static/cs/wallpaper/mirage.webp",
    radar: ["https://assets.csnades.gg/mirage_game_radar_dfb164f478.webp"],
  },
  {
    name: "Nuke",
    logo: "/static/cs/logo/nukeLogo.webp",
    image: "/static/cs/wallpaper/nuke.jpg",
    radar: [
      "https://assets.csnades.gg/nuke_game_radar_9276ffd1a4.webp",
      "https://assets.csnades.gg/nuke_game_radar_lower_b42d4863bf.webp",
    ],
  },
  {
    name: "Overpass",
    logo: "/static/cs/logo/overpassLogo.webp",
    image: "/static/cs/wallpaper/overpass.jpg",
    radar: ["https://assets.csnades.gg/overpass_game_radar_454d8227ee.webp"],
  },
  {
    name: "Vertigo",
    logo: "/static/cs/logo/vertigoLogo.webp",
    image: "/static/cs/wallpaper/vertigo.png",
    radar: [
      "https://assets.csnades.gg/vertigo_game_radar_fdb7e7081d.webp",
      "https://assets.csnades.gg/vertigo_game_radar_2_1f01133fe9.webp",
    ],
  },
];

export const anubisPositions = [
  "All positions",
  "A Main",
  "A-Con (Camera)",
  "Alley",
  "Backsite A",
  "Backsite B",
  "Boat",
  "Bridge",
  "Broken wall",
  "B Main",
  "CT",
  "Connector",
  "Corner",
  "Doors",
  "Fountain",
  "Heaven",
  "Headshot",
  "House",
  "Mid",
  "Ninja",
  "Palace",
  "Pillar",
  "Ruins",
  "Sniper",
  "Stairs",
  "Temple(palace)",
  "Tetris(upper)",
  "Top Mid",
  "Water",
];

export const ancientPositions = [
  "All positions",
  "Sniper Nest",
  "Red",
  "Top Mid",
  "Cubby",
  "Elbow",
  "Tetris/Xbox",
  "Elbow",
  "Donut(Mid)",
  "Donut(Site)",
  "Window(Construction/snake)",
  "Cheetah",
  "Cave",
  "Lane",
  "Wood/Ninja",
  "Long",
  "Short",
  "Ramp",
  "Door",
  "Outside B",
  "Yard(split)",
  "A Main",
  "Boost",
  "Bigbox",
  "Platform",
  "Single",
  "Triple",
  "Temple",
];

export const nukePositions1 = [
  "All positions",
  "Roof",
  "Lobby",
  "Squeaky",
  "Trophy",
  "Control",
  "BigBox",
  "Ramp",
  "Ramp Room",
  "Headshot",
  "Acces",
  "Stack",
  "Admin",
  "Hell",
  "Locker",
  "catwalk",
  "ctred",
  "garage",
  "secret",
  "T red",
  "outside",
  "silo",
  "mini(main)",
  "venttetris",
  "rafters",
  "hut",
];

export const nukePositions2 = [
  "All positions",
  "Ramp",
  "Toxic",
  "Dark",
  "Lower",
  "Obs",
  "Doors",
  "Decon(single)",
  "vents",
  "black halls",
  "tunnels",
  "secret",
];

export const vertigoPositions1 = [
  "All positions",
  "Connector",
  "Electric",
  "Siteb",
  "Backb(quad)",
  "catwalk(white)",
  "Stairs",
  "Headshot",
  "top mid",
  "boost",
  "mid",
  "iron",
  "tmid",
  "generator",
  "tstairs",
  "ladder",
  "heaven",
  "door",
  "elevator",
  "double(headshot)",
  "asite",
  "sandbags",
  "lane(yellow)",
  "short",
  "scaffold",
  "t ramp",
];

export const vertigoPositions2 = [
  "All positions",
  "sandbags",
  "fence",
  "a ramp",
  "scaffold",
  "big box",
  "sheets",
  "bridge",
  "save spot",
  "ladder",
  "underpass",
  "b stairs",
  "under stairs",
  "toilets",
  "stair",
];

export const infernoPositions = [
  "All positions",
  "Ledge",
  "T Ramp",
  "Bridge",
  "Balcony",
  "T Apps",
  "2nd Mid",
  "Back Alley",
  "Window",
  "Stairs",
  "CT Apps",
  "Mini-pit",
  "Cemetery",
  "Graveyard",
  "Truck A",
  "A Short",
  "Close Left",
  "A Site",
  "Back Site",
  "Top Mid",
  "Bench",
  "Bottom Mid",
  "Underpass(Mexico/Rat)",
  "Boiler",
  "A Long",
  "Long Corner",
  "Library",
  "Kitchen",
  "Speed Way",
  "Terrace",
  "Well",
  "Tree",
  "Truck",
  "Construction/Church",
  "Sand Bags",
  "Garden(back coffin)",
  "Coffins",
  "Dark",
  "Fountain",
  "Quad",
  "2nd",
  "1st",
  "Boost",
  "Car",
  "Logs",
  "Boost A",
  "Arch",
  "Pool/Grill",
  "Porch/Roof",
];

export const miragePositions = [
  "All positions",
  "CT",
  "Ticket booth",
  "Ninja",
  "Noob",
  "Firebox/Ninja",
  "Triple Box",
  "Balcony",
  "Stairs",
  "Jungle",
  "Sandwitch",
  "Tetris",
  "A Ramp",
  "Shadows/Under Palace",
  "Palace",
  "Pillars",
  "T Roof",
  "Connector",
  "Top Connector",
  "Window(sniper nest)",
  "Vent",
  "Ladder Room",
  "Underpass",
  "B Short",
  "Catwalk",
  "Mid",
  "Chair",
  "Top Mid",
  "Mid Boxes",
  "Side Alley",
  "Cart",
  "Apps Ramp",
  "TV",
  "House",
  "Back Alley",
  "Kitchen",
  "Short Corner/Edward",
  "B Apps",
  "B Plat",
  "Van",
  "B Default",
  "Boost Boxes",
  "Bench",
  "Forest",
  "B Site",
  "Arches",
  "B Short",
  "E Box",
  "Empty/Backsite",
  "Door/Long",
  "Window",
  "Sneaky",
  "Market",
];

export const overpassPositions = [
  "All positions",
  "Upper Tunnels",
  "Playground",
  "Fountain",
  "Hitmarket",
  "Rock",
  "Tree",
  "A Long",
  "Long Loost",
  "Long Toilets",
  "Bench",
  "Cafe",
  "Party",
  "Mid",
  "Toilets",
  "Connector",
  "A Short",
  "Flowers",
  "Sign Post",
  "Close Left",
  "Van",
  "Bank",
  "Truck",
  "Trash(Bins)",
  "Storage",
  "Heaven",
  "Walkway",
  "Graffity",
  "Pit",
  "Pillar",
  "Barrels",
  "Sewers",
  "Sand Bags",
  "Water",
  "Boost",
  "Wqueaky",
  "Short Tunnel",
  "Tracks",
  "Monster",
  "Alley",
];

export const hardcodedPositions: HardcodedPositions = {
  Anubis: {
    Heaven: { top: "21.5", left: "71.7" },
    "Backsite A": { top: "20", left: "79" },
    Fountain: { top: "26", left: "85" },
    Connector: { top: "61", left: "42" },
    "Broken wall": { top: "31", left: "68.5" },
    Palace: { top: "33", left: "55" },
    "A Main": { top: "36", left: "84.6" },
    "A-Con (Camera)": { top: "37.7", left: "64" },
    Mid: { top: "40", left: "56.5" },
    House: { top: "49", left: "50.5" },
    Doors: { top: "51", left: "57" },
    Headshot: { top: "45", left: "72.5" },
    Boat: { top: "54", left: "70" },
    Water: { top: "60", left: "60" },
    "Tetris(upper)": { top: "53", left: "77" },
    Stairs: { top: "65", left: "67.5" },
    "Top Mid": { top: "63", left: "49.8" },
    Alley: { top: "76", left: "63" },
    Bridge: { top: "60", left: "50" },
    Ruins: { top: "72", left: "27" },
    "B Main": { top: "56", left: "22" },
    Corner: { top: "49", left: "22.5" },
    Pillar: { top: "58", left: "29.5" },
    "Backsite B": { top: "47", left: "35" },
    "Temple(palace)": { top: "43", left: "34" },
    Ninja: { top: "52.5", left: "39.5" },
    CT: { top: "43", left: "28" },
    Sniper: { top: "30", left: "28.5" },
  },
  Ancient: {
    "Sniper Nest": { top: "25", left: "48" },
    Red: { top: "33", left: "48.5" },
    "Top Mid": { top: "38", left: "48.5" },
    Cubby: { top: "46.5", left: "56" },
    Elbow: { top: "58", left: "38" },
    "Window(Construction/snake)": { top: "58", left: "66.2" },
    Cheetah: { top: "53.5", left: "66.2" },
    Cave: { top: "41", left: "72.5" },
    Lane: { top: "60.5", left: "71" },
    "Wood/Ninja": { top: "48.5", left: "78" },
    Long: { top: "35", left: "91" },
    Short: { top: "32", left: "78" },
    Ramp: { top: "52", left: "93" },
    Door: { top: "63", left: "88" },
    "Tetris/Xbox": { top: "60", left: "53" },
    "Donut(Mid)": { top: "45.5", left: "35" },
    "Donut(Site)": { top: "33", left: "27.5" },
    "Outside B": { top: "73", left: "86" },
    "Yard(split)": { top: "73", left: "25" },
    "A Main": { top: "39", left: "9" },
    Boost: { top: "33", left: "15" },
    Bigbox: { top: "21", left: "17" },
    Platform: { top: "16", left: "10" },
    Single: { top: "19", left: "12" },
    Temple: { top: "17", left: "27" },
    Triple: { top: "24", left: "32" },
  },
  Inferno: {
    Ledge: { top: "62", left: "29" },
    "T Ramp": { top: "63", left: "37" },
    Bridge: { top: "84", left: "32" },
    Balcony: { top: "85.5", left: "83.5" },
    "T Apps": { top: "91", left: "35" },
    "2nd Mid": { top: "84", left: "38" },
    "Back Alley": { top: "95.6", left: "53" },
    Window: { top: "84", left: "61" },
    Stairs: { top: "77", left: "60" },
    "CT Apps": { top: "88.4", left: "70" },
    "Mini-pit": { top: "86", left: "86" },
    Cemetery: { top: "83", left: "95" },
    Graveyard: { top: "71", left: "95" },
    "Truck A": { top: "82.5", left: "80" },
    "A Short": { top: "80", left: "76" },
    "Porch/Roof": { top: "82.5", left: "71" },
    "A Site": { top: "71", left: "83.5" },
    "Back Site": { top: "67", left: "80.5" },
    "Top Mid": { top: "70", left: "68" },
    Bench: { top: "67", left: "59.5" },
    "Bottom Mid": { top: "71", left: "42" },
    "Underpass(Mexico/Rat)": { top: "67", left: "46" },
    Boiler: { top: "74.5", left: "67" },
    "A Long": { top: "59", left: "71.5" },
    "Long Corner": { top: "55", left: "69" },
    Library: { top: "57", left: "93" },
    Kitchen: { top: "50", left: "93" },
    "Speed Way": { top: "30", left: "76" },
    Terrace: { top: "31", left: "81" },
    Well: { top: "25", left: "83" },
    Tree: { top: "22.5", left: "68.5" },
    Truck: { top: "16", left: "70" },
    "Construction/Church": { top: "12", left: "63" },
    "Sand Bags": { top: "40", left: "57" },
    "Garden(back coffin)": { top: "5", left: "51.5" },
    Coffins: { top: "13", left: "51.5" },
    Dark: { top: "11", left: "41" },
    Fountain: { top: "21", left: "47.8" },
    Quad: { top: "24", left: "41" },
    "2nd": { top: "27", left: "47" },
    "1st": { top: "27", left: "50.5" },
    Boost: { top: "27", left: "52.5" },
    Car: { top: "35.5", left: "49.5" },
    Arch: { top: "51", left: "79.7" },
    Logs: { top: "51", left: "40" },
    "Boost A": { top: "76", left: "80" },
    "Pool/Grill": { top: "18", left: "56" },
  },
  Mirage: {
    CT: { top: "91", left: "41" },
    "Ticket Booth": { top: "94.5", left: "43.5" },
    Noob: { top: "91", left: "54.5" },
    "Firebox/Ninja": { top: "91", left: "59" },
    "Triple Box": { top: "84", left: "47.5" },
    Balcony: { top: "82", left: "65" },
    Palace: { top: "89", left: "66" },
    Stairs: { top: "70", left: "53.5" },
    Jungle: { top: "66", left: "42" },
    Sandwitch: { top: "69", left: "56.8" },
    Tetris: { top: "66", left: "61.5" },
    "A Ramp": { top: "68", left: "70" },
    "Shadows/Under Palace": { top: "79", left: "67" },
    Pillars: { top: "86", left: "76" },
    "T Roof": { top: "67", left: "83" },
    Connector: { top: "55", left: "48.7" },
    "Top Connector": { top: "61", left: "48.7" },
    "Window(sniper nest)": { top: "44", left: "38" },
    Vent: { top: "38", left: "36.9" },
    "Ladder Room": { top: "30", left: "40" },
    Underpass: { top: "40", left: "40.5" },
    "B Short": { top: "23", left: "45" },
    Catwalk: { top: "38", left: "55" },
    Mid: { top: "45", left: "55" },
    Chair: { top: "51", left: "56.5" },
    "Top Mid": { top: "36", left: "71" },
    "Mid Boxes": { top: "45", left: "74" },
    "Side Alley": { top: "18", left: "91" },
    Cart: { top: "10", left: "72" },
    "Apps Ramp": { top: "10", left: "82" },
    TV: { top: "5", left: "77" },
    House: { top: "5", left: "70" },
    "Back Alley": { top: "11.5", left: "54" },
    Kitchen: { top: "15", left: "38.5" },
    "Short Corner/Edward": { top: "14", left: "34" },
    "B Apps": { top: "7", left: "24" },
    "B Plat": { top: "5", left: "17" },
    Van: { top: "6", left: "13" },
    "B Default": { top: "15", left: "16" },
    "Boost Boxes": { top: "16.5", left: "19" },
    Forest: { top: "14", left: "3.5" },
    Bench: { top: "19", left: "5" },
    "B Site": { top: "20", left: "16" },
    Arches: { top: "20", left: "32" },
    "E Box": { top: "32", left: "27" },
    "Empty/Backsite": { top: "28", left: "16" },
    "Door/Long": { top: "35", left: "10" },
    Window: { top: "35", left: "19" },
    Sneaky: { top: "45", left: "11" },
    Market: { top: "42", left: "18" },
  },
};
