export const acceptedRouteNames: string[] = ["scrap", "statues", "treasures"];
export const acceptedRouteGames: string[] = ["cs", "gta"];

export const Locations: string[] = [
  "All locations",
  "Calafia",
  "Sawmill",
  "Timber tunnel",
  "Gino's place",
  "First bridge",
  "Second bridge",
  "Plane",
  "Epsylon",
  "Farm",
  "Chilliad",
  "Ranch",
  "Paleto",
  "FZ",
  "Behind SAHP",
];

export type MapsState = {
  name: string;
  logo: string;
  image: string;
  radar: string[];
};

export const Maps: MapsState[] = [
  {
    name: "Anubis",
    logo: "/static/cs/logo/anubisLogo.png",
    image: "/static/cs/wallpaper/anubis.jpg",
    radar: ["https://assets.csnades.gg/anubis_game_radar_7bada7b5e9.webp"],
  },
  {
    name: "Ancient",
    logo: "/static/cs/logo/ancientLogo.webp",
    image: "/static/cs/wallpaper/ancient.jpg",
    radar: ["https://assets.csnades.gg/ancient_game_radar_14875e0cb1.webp"],
  },
  {
    name: "Inferno",
    logo: "/static/cs/logo/infernoLogo.png",
    image: "/static/cs/wallpaper/inferno.jpeg",
    radar: ["https://assets.csnades.gg/inferno_game_radar_bbecda6217.webp"],
  },
  {
    name: "Mirage",
    logo: "/static/cs/logo/mirageLogo.png",
    image: "/static/cs/wallpaper/mirage.webp",
    radar: ["https://assets.csnades.gg/mirage_game_radar_dfb164f478.webp"],
  },
  {
    name: "Nuke",
    logo: "/static/cs/logo/nukeLogo.webp",
    image: "/static/cs/wallpaper/nuke.jpg",
    radar: [
      "https://assets.csnades.gg/nuke_game_radar_9276ffd1a4.webp",
      "https://assets.csnades.gg/nuke_game_radar_lower_b42d4863bf.webp",
    ],
  },
  {
    name: "Overpass",
    logo: "/static/cs/logo/overpassLogo.webp",
    image: "/static/cs/wallpaper/overpass.jpg",
    radar: ["https://assets.csnades.gg/overpass_game_radar_454d8227ee.webp"],
  },
  {
    name: "Vertigo",
    logo: "/static/cs/logo/vertigoLogo.webp",
    image: "/static/cs/wallpaper/vertigo.png",
    radar: [
      "https://assets.csnades.gg/vertigo_game_radar_fdb7e7081d.webp",
      "https://assets.csnades.gg/vertigo_game_radar_2_1f01133fe9.webp",
    ],
  },
];

export const anubisPositions = [
  "All positions",
  "Heaven",
  "BackSite",
  "Foundtain",
  "A Main",
  "Camera",
  "Mid",
  "House",
  "Door",
  "Headshot",
  "boat",
  "water",
  "tetris(upper)",
  "stairs",
  "top mid",
  "alley",
  "bridge",
  "ruins",
  "b main",
  "corner(platform/pizza)",
  "pillar",
  "backsite",
  "ninja",
  "ct",
  "sniper",
  "temple(palace)",
];

export const ancientPositions = [
  "All positions",
  "Sniper Nest",
  "Red",
  "Top Mid",
  "Cubby",
  "Elbow",
  "Window(Construction/snake)",
  "Cheetah",
  "Cave",
  "Lane",
  "Wood",
  "Long",
  "short",
  "Ramp",
  "Door",
  "Outside B",
  "Yard(split)",
  "a main",
  "Boost",
  "Bigbox",
  "Platform",
  "Single",
  "Triple",
  "Temple",
];

export const nukePositions1 = [
  "All positions",
  "Roof",
  "Lobby",
  "Squeaky",
  "Trophy",
  "Control",
  "BigBox",
  "Ramp",
  "Ramp Room",
  "Headshot",
  "Acces",
  "Stack",
  "Admin",
  "Hell",
  "Locker",
  "catwalk",
  "ctred",
  "garage",
  "secret",
  "T red",
  "outside",
  "silo",
  "mini(main)",
  "venttetris",
  "rafters",
  "hut",
];

export const nukePositions2 = [
  "All positions",
  "Ramp",
  "Toxic",
  "Dark",
  "Lower",
  "Obs",
  "Doors",
  "Decon(single)",
  "vents",
  "black halls",
  "tunnels",
  "secret",
];

export const vertigoPositions1 = [
  "All positions",
  "Connector",
  "Electric",
  "Siteb",
  "Backb(quad)",
  "catwalk(white)",
  "Stairs",
  "Headshot",
  "top mid",
  "boost",
  "mid",
  "iron",
  "tmid",
  "generator",
  "tstairs",
  "ladder",
  "heaven",
  "door",
  "elevator",
  "double(headshot)",
  "asite",
  "sandbags",
  "lane(yellow)",
  "short",
  "scaffold",
  "t ramp",
];

export const vertigoPositions2 = [
  "All positions",
  "sandbags",
  "fence",
  "a ramp",
  "scaffold",
  "big box",
  "sheets",
  "bridge",
  "save spot",
  "ladder",
  "underpass",
  "b stairs",
  "under stairs",
  "toilets",
  "stair",
];

export const infernoPositions = [
  "All positions",
  "ledge",
  "t ramp",
  "living room",
  "bridgee",
  "balcony",
  "t apps",
  "2nd mid",
  "2mid door",
  "back alley",
  "window",
  "stairs",
  "ct apps",
  "close apps",
  "balcony",
  "pit dosia",
  "cemetary",
  "graveyard",
  "truck a",
  "a short",
  "patio",
  "close left",
  "a site",
  "back site",
  "top mid",
  "bench",
  "bottom mid",
  "underpass(mexico/rat)",
  "boiler",
  "a long",
  "long corner",
  "library",
  "kitchen",
  "speed way",
  "terrace",
  "well",
  "tree",
  "truck",
  "construction",
  "sand bags",
  "garden(spate coffin)",
  "coffins",
  "dark",
  "fountain",
  "quad",
  "2nd",
  "1st",
  "boost",
  "sand bags",
  "car",
  "logs",
];

export const miragePositions = [
  "All positions",
  "Ct",
  "ticket booth",
  "ninja",
  "firebox",
  "triple box",
  "balcony",
  "stairs",
  "jungle",
  "sandwitch",
  "tetris",
  "a ramp",
  "shadows",
  "palace",
  "pillars",
  "palace",
  "t roof",
  "connector",
  "window(sniper nest)",
  "vent",
  "ladder room",
  "underpass",
  "b short",
  "catwalk",
  "mid",
  "chair",
  "top mid",
  "mid boxes",
  "side alley",
  "cart",
  "apps ramp",
  "tv",
  "house",
  "back alley",
  "underpass",
  "kitchen",
  "short corner",
  "b apps",
  "b plat",
  "van",
  "b default",
  "boost boxes",
  "bench",
  "b site",
  "arches",
  "b short",
  "e box",
  "empty",
  "door",
  "window",
  "sneaky",
  "market",
];

export const overpassPositions = [
  "All positions",
  "upper tunnels",
  "playground",
  "fountain",
  "hitmarket",
  "rock",
  "tree",
  "a long",
  "long boost",
  "long toilets",
  "bench",
  "cafe",
  "party",
  "mid",
  "toilets",
  "connector",
  "a short",
  "flowers",
  "sign post",
  "close left",
  "van",
  "bank",
  "truck",
  "trash(bins)",
  "storage",
  "heaven",
  "walkway",
  "graffity",
  "pit",
  "pillar",
  "barrels",
  "sewers",
  "sand bags",
  "water",
  "boost",
  "squeaky",
  "short tunnel",
  "tracks",
  "monster",
  "alley",
];
